name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  plot_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python 3.12
      uses: actions/setup-python@v7
      with:
        python-version: 3.12

    - name: Install dependencies
      env:
        # Need to be of format repo:branch.
        BENCHOPT_BRANCH: benchopt:main
      run: |
        pip install -r requirements.txt

        USER=${BENCHOPT_BRANCH%:*}
        BRANCH=${BENCHOPT_BRANCH##*:}
        echo "using branch $USER:$BRANCH"
        pip install -U git+https://github.com/$USER/benchOpt@$BRANCH
    - name: Render
      run: |
        make render

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: html
